//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGCPlug_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLogin
    {
        public int Id { get; set; }
        public string BusinessName { get; set; }
        public string BusinessEmail { get; set; }
        public string PasswordHash { get; set; }
        public string BusinessId { get; set; }
    }
}
